export const toolPaths = [
  'repliers/repliers-api/property-types-styles.js',
  'repliers/repliers-api/get-deleted-listings.js',
  'repliers/repliers-api/areas-cities-and-neighborhoods.js',
  'repliers/repliers-api/get-address-history.js',
  'repliers/repliers-api/buildings.js',
  'repliers/repliers-api/get-a-listing.js',
  'repliers/repliers-api/find-similar-listings.js',
  'repliers/repliers-api/search.js',
  'repliers/repliers-api/nlp-search.js',
  'repliers/repliers-api/get-places.js',
  'repliers/repliers-api/locations-autocomplete.js',
  'repliers/repliers-api/search-locations.js',
  'repliers/repliers-api/search-offices.js',
  'repliers/repliers-api/get-nlp-history.js',
];
